feign:
  url-account-service: localhost:8086/account-ms
  url-auth-service: localhost:8084/auth-ms
jwt:
  secret: sampletest
logging:
  level:
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql: trace
      springframework: info
  pattern:
    console: '%d{dd-MM-yy} %d{HH:mm:ss.SSS} %-20.20thread %5p %-25.25logger{25} %25M
      %4L %m%n'
server:
  error:
    include-stacktrace: never
  port: 8085
  servlet:
    context-path: /customer
spring:
  application:
    name: customer
  datasource:
    driver-class-name: org.h2.Driver
    password: root
    url: jdbc:h2:mem:customer
    username: root
  devtools:
    livereload:
      port: 35777
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      hbm2ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
